root: true
env:
  node: true
parser: 'vue-eslint-parser'
parserOptions:
  parser: '@typescript-eslint/parser'
  ecmaVersion: 'latest'
  sourceType: 'module'
  ecmaFeatures: { jsx: true }
extends:
  - 'plugin:vue/vue3-essential'
  - 'plugin:vue/vue3-recommended'
  - 'plugin:vue/vue3-strongly-recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'prettier'
  - 'plugin:prettier/recommended'
rules: {
    'vue/multi-word-component-names': 'off',
    'no-var': 'error', #	要求使用 let 或 const 而不是 var
    'vue/html-indent': [2],
  }
